apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geoserver

resources:
  - namespace.yaml

helmCharts:
  - name: geoserver
    repo: https://opensource.ncsa.illinois.edu/charts/
    releaseName: ncsa
    namespace: geoserver
    version: 1.2.0
    valuesFile: values.yaml
